# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19237f9e79bbe0e6a758d3afac71351ca512cbcea7e7482b9440532d420aaea0c8e8ef2e9a83104613adc5992dfb7f06ab2bf41c99e5d6fe9d82b3d2e3e59cef

test:
  secret_key_base: 4bd6fb1480abf04e998afee0df21b9d9eeb728b5b52bec14837ba588d2b271e9971e0a2a4cae6c9ec2c3cb409e9051f15f2b0e5f9a019c1aa0971186e506cfa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
